services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    environment:
      - PUID=1000 #"id $user" to find your uid & gid values
      - PGID=1000
    volumes:
      - /data/server-sync:/srv
      - ./database:/filebrowser/database
      - ./config:/filebrowser/config
    ports:
      - 8081:80 
    restart: unless-stopped
